name: Fetch YTM Unlisted

on:
  workflow_dispatch:

jobs:
  get-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          # Downloads the latest yt-dlp binary directly
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Run Script
        run: python get_playlist.py
